### PR TITLE
Allow setup script to run on Fedora/RHEL/CENTOS systems

### PR DESCRIPTION
**Pull request by pboyd04**
Redhat based system don't allow users to run docker command without sudo.

### CODE REVIEW

**Comment by russelltsherman** [comment]
by creating a docker group and assigning your user to it you should be able to run docker commands without sudo

https://developer.fedoraproject.org/tools/docker/docker-installation.html

**Comment by russelltsherman** [comment]
i'm not against incorporating this change if there is a compelling reason why adding the docker group isn't ideal..

**Comment by pboyd04** [comment]
It's a peculiarity of Redhat. They don't have a docker group. The socket is root:root. http://www.projectatomic.io/blog/2015/08/why-we-dont-let-non-root-users-run-docker-in-centos-fedora-or-rhel/

**Comment by russelltsherman** [comment]
that blog post was about a year and a half ago.. have you tried to create a docker group and restart docker? I'm thinking you'll find that the socket is created differently.. 

if we merge PR this then we should add the $prefix to ALL the scripted docker calls in the package and add a blurb about the .usesudo file in the readme...

**Comment by pboyd04** [comment]
From my system:
[pboyd@route1 DevSandbox (Fedora1)]$ ls -al /var/run/docker.sock
srw-rw----. 1 root root 0 Apr 18 17:10 /var/run/docker.sock

And yes I tried the docker group (it didn't exist). Creating it didn't do anything.

**Comment by russelltsherman** [comment]
do you know if there is a reliable way this setup script could detect that it was running on redhat and  automagically write the .usesudo file?

**Comment by pboyd04** [comment]
check for /etc/redhat-release  maybe?

**Comment by russelltsherman** [comment]
please review changes.. 
i prefixed all the docker commands in bin and made an attempt to create the usesudo file automagically

**Comment by pboyd04** [comment]
Looks good to me. Will probably help me fix the other issues I'm running into (stupid SELinux...)

**Review by russelltsherman — APPROVED** [review]

**Pull request merged**
